/*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
		               Kefan-Zheng,  2021   		
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
#include "type.h"
#include "stdio.h"
#include "const.h"
#include "protect.h"
#include "string.h"
#include "fs.h"
#include "proc.h"
#include "tty.h"
#include "console.h"
#include "global.h"
#include "proto.h"

#define DELAY_TIME 2500

void anim(){
	char str[15] = "loading...";
	clear();
	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [/...............................................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();
	
	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [##########/.....................................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [##########|.....................................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [##########-.....................................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [####################/...........................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [####################|...........................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [####################-...........................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [#############################/..................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [#############################|..................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [#############################-..................]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [######################################/.........]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [######################################|.........]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [######################################-.........]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);
	clear();

	printf(" ==============================================================================\n");
	printf(" #                                                                            #\n");
	printf(" #                                                                            #\n");
	printf(" #                                   #                                        #\n");
	printf(" #                                 ##                                         #\n");
	printf(" #                               ###                                          #\n");
	printf(" #                             ####                                           #\n");
	printf(" #               @@@@@       #####     @@@@@                                  #\n");
	printf(" #             @@@         #######        @@@                                 #\n");
	printf(" #          @@@          ################    @@@                              #\n");
	printf(" #         @@          ################        @@       Designed              #\n");
	printf(" #         @         ################           @          by                 #\n");
	printf(" #         @@               #######            @@      kefan-Zheng            #\n");
	printf(" #          @@@            ######            @@@       TONGJI UNIV.           #\n");
	printf(" #             @@@        #####           @@@            2021.8               #\n");
	printf(" #               @@@@@   ####        @@@@@@                                   #\n");
	printf(" #                   @@@@@@@@@@@@@@@@@                                        #\n");
	printf(" #                     ##                                                     #\n");
	printf(" #                    #                                                       #\n");
	printf(" #                                                                            #\n");
	printf(" #        [################################################]loading...        #\n");
	printf(" #                                                                            #\n");
	printf(" #          WELCOME TO LightningOS! ENJOY YOUR JOURNEY OF EXPLORATION!        #\n");
	printf(" #                                                                            #\n");
	printf(" ==============================================================================\n");
	milli_delay(DELAY_TIME);

}
